# Generated by Django 3.0.7 on 2020-07-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
