# Generated by Django 3.0.7 on 2020-07-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_api_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='download_count',
        ),
    ]
