# Generated by Django 2.1.15 on 2020-06-26 04:33

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='tomas.png', upload_to='accounts'),
        ),
    ]
