# Generated by Django 2.1.15 on 2020-06-26 04:38

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200626_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='default.png', upload_to='accounts'),
        ),
    ]
